// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "KeepPingPong",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "KeepPingPong",
            targets: ["AppModule"],
            bundleIdentifier: "naoki.takahashi.balanceGameAR",
            teamIdentifier: "CW97U5J24N",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "aa"),
                .fileAccess(.pictureFolder, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readOnly),
                .fileAccess(.moviesFolder, mode: .readOnly),
                .fileAccess(.userSelectedFiles, mode: .readOnly)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)